ForumApp/Models/Forum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Services.Description;

namespace ForumApp.Models
{
    public class Forum
    {
        public int ForumId { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        public virtual ICollection<Post> Posts { get; set; }
        public Forum()
        {
            Posts = new HashSet<Post>();
        }


    }
}

ForumApp/Controllers/PostsController.cs
using ForumApp.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity.Owin;

namespace ForumApp.Controllers
{
    [Authorize(Roles = "Admin,Moderator,User")]
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts/Details/5
        // PostsController.cs - In the Details action
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var post = db.Posts
                .Include(p => p.Votes)
                .Include(p => p.Comments.Select(c => c.Votes))
                .FirstOrDefault(p => p.PostId == id);
            post.Content = String.Empty;

            if (post == null)
            {
                return HttpNotFound();
            }

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var roles = userManager.GetRoles(post.UserId);
            ViewBag.UserRole = roles.FirstOrDefault() ?? "User"; // Assign a default role if none is found

            var userId = User.Identity.GetUserId();
            ViewBag.UserPostVoteType = post.Votes.FirstOrDefault(v => v.UserId == userId)?.VoteType ?? 0;

            // Pass similar information for comments if needed

            //can you make a breadcrumb here?
            var breadcrumb= new List<BreadcrumbItem>
            {
                new BreadcrumbItem { Title = "Forums", Url = Url.Action("Index","Forums") },
                new BreadcrumbItem { Title = post.Forum.Title, Url = Url.Action("Details", "Forums", new { id = post.ForumId }) },
                new BreadcrumbItem { Title = post.Title, IsActive=true}
            };

            ViewBag.Breadcrumbs = breadcrumb;    

            return View(post);
        }


        // GET: Posts/Create
        public ActionResult Create(int forumId)
        {
            var forum = db.Forums.Find(forumId);
            if (forum == null)
            {
                return HttpNotFound();
            }

            ViewBag.ForumId = forumId;
            ViewBag.ForumTitle = forum.Title;
            return View();
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                post.UserId = User.Identity.GetUserId();

                if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                {
                    post.IsApproved = true;
                    db.Posts.Add(post);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Forums", new { id = post.ForumId}); 
                }
                post.IsApproved = false; // Post is not approved by default
                db.Posts.Add(post);
                db.SaveChanges();

                return RedirectToAction("Details", "Forums", new { id = post.ForumId, postSubmitted = true }); // Redirect to a confirmation page
            }
            ViewBag.ForumId = post.ForumId; // proveri ova zasto se prakja

            return View(post);
        }

        /* [HttpPost]
         public ActionResult Up



         Post(int postId)
         {
             var post = db.Posts.Find(postId);
             if (post != null)
             {
                 post.Upvotes++;
                 db.SaveChanges();
                 return Json(new { success = true, upvotes = post.Upvotes });
             }
             return Json(new { success = false });
         }

         [HttpPost]
         public ActionResult DownvotePost(int postId)
         {
             var post = db.Posts.Find(postId);
             if (post != null)
             {
                 post.Downvotes++;
                 db.SaveChanges();
                 return Json(new { success = true, downvotes = post.Downvotes });
             }
             return Json(new { success = false });
         }
 */
        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult DeletePost(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Details", "Forums", new { id = post.ForumId });
        }


        [Authorize(Roles = "Admin")]
        public ActionResult PostPendingApproval()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult PendingApproval()
        {
            var pendingPosts = db.Posts.Where(p => !p.IsApproved).ToList();
            return View(pendingPosts);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Approve(int id)
        {
            var post = db.Posts.Find(id);
            if (post != null)
            {
                post.IsApproved = true;
                db.SaveChanges();
            }

            return RedirectToAction("PendingApproval"); // Redirect back to the pending posts list
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Disapprove(int id)
        {
            var post = db.Posts.Find(id);
            if (post != null)
            {
                db.Posts.Remove(post); // Remove the post from the database
                db.SaveChanges();
            }

            return RedirectToAction("PendingApproval"); // Redirect back to the pending posts list
        }



        [HttpPost]
        [Authorize]
        public ActionResult UpvotePost(int postId)
        {
            var userId = User.Identity.GetUserId();
            var existingVote = db.PostVotes.FirstOrDefault(v => v.PostId == postId && v.UserId == userId);

            if (existingVote != null)
            {
                if (existingVote.VoteType == 1)
                {
                    // User clicked upvote again, remove the vote
                    db.PostVotes.Remove(existingVote);
                }
                else
                {
                    // Change vote from downvote to upvote
                    existingVote.VoteType = 1;
                    existingVote.DateVoted = DateTime.Now;
                    db.Entry(existingVote).State = EntityState.Modified;
                }
            }
            else
            {
                // Add new upvote
                var vote = new PostVote
                {
                    PostId = postId,
                    UserId = userId,
                    VoteType = 1,
                    DateVoted = DateTime.Now
                };
                db.PostVotes.Add(vote);
            }

            db.SaveChanges();

            // Recalculate vote counts
            var post = db.Posts.Include(p => p.Votes).FirstOrDefault(p => p.PostId == postId);
            return Json(new { success = true, upvotes = post.Upvotes, downvotes = post.Downvotes });
        }


        [HttpPost]
        [Authorize]
        public ActionResult DownvotePost(int postId)
        {
            var userId = User.Identity.GetUserId();
            var existingVote = db.PostVotes.FirstOrDefault(v => v.PostId == postId && v.UserId == userId);

            if (existingVote != null)
            {
                if (existingVote.VoteType == -1)
                {
                    // User clicked downvote again, remove the vote
                    db.PostVotes.Remove(existingVote);
                }
                else
                {
                    // Change vote from upvote to downvote
                    existingVote.VoteType = -1;
                    existingVote.DateVoted = DateTime.Now;
                    db.Entry(existingVote).State = EntityState.Modified;
                }
            }
            else
            {
                // Add new downvote
                var vote = new PostVote
                {
                    PostId = postId,
                    UserId = userId,
                    VoteType = -1,
                    DateVoted = DateTime.Now
                };
                db.PostVotes.Add(vote);
            }

            db.SaveChanges();

            // Recalculate vote counts
            var post = db.Posts.Include(p => p.Votes).FirstOrDefault(p => p.PostId == postId);
            return Json(new { success = true, upvotes = post.Upvotes, downvotes = post.Downvotes });
        }






    }
}

ForumApp/Controllers/ProfileController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using ForumApp.Models;
using Microsoft.AspNet.Identity;

namespace ForumApp.Controllers
{
    public class ProfileController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Profile
        public ActionResult Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.Users.Include(u => u.Posts)
                       .Include(u => u.Comments)
                       .FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            // Calculate total upvotes and downvotes from posts
            var totalPostUpvotes = user.Posts.Sum(p => p.Upvotes);
            var totalPostDownvotes = user.Posts.Sum(p => p.Downvotes);

            // Calculate total upvotes and downvotes from comments
            var totalCommentUpvotes = user.Comments.Sum(c => c.Upvotes);
            var totalCommentDownvotes = user.Comments.Sum(c => c.Downvotes);

            // Total upvotes and downvotes
            user.TotalUpvotes = totalPostUpvotes + totalCommentUpvotes;
            user.TotalDownvotes = totalPostDownvotes + totalCommentDownvotes;

            return View(user);
        }


        // GET: Profile/Edit
        public ActionResult Edit()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.FirstOrDefault(u => u.Id == userId);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: Profile/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var user = db.Users.FirstOrDefault(u => u.Id == userId);

                if (user != null)
                {
                    //user.UserName = model.UserName;
                    user.ProfilePictureUrl = model.ProfilePictureUrl;

                    db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                    await db.SaveChangesAsync();
                }

                return RedirectToAction("Index",new {id=userId});
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult UserPosts(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.Users.Include(u => u.Posts).FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.UserName = user.UserName;

            return View(user.Posts); // Return the list of posts to the view
        }

        [HttpGet]
        public ActionResult UserComments(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = db.Users.Include(u => u.Comments.Select(c => c.Post)).FirstOrDefault(u => u.Id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.UserName = user.UserName;
            ViewBag.UserId = user.Id; 


            return View(user.Comments); // Return the list of comments to the view
        }

    }
}

ForumApp/Views/Forums/Create.cshtml
@model ForumApp.Models.Forum

@{
    ViewBag.Title = "Create Forum";
}

<link rel="stylesheet" type="text/css" href="~/Content/Forum/ForumCreate.css" />


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <!-- Card Container -->
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Create a New Forum</h4>
                </div>

                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "form-label" })
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter forum title" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger mt-1" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-label" })
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 4, placeholder = "Enter forum description" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger mt-1" })
                        </div>

                        <div class="d-flex justify-content-end">
                            <input type="submit" value="Create" class="btn btn-success px-4" />
                            <a href="@Url.Action("Index")" class="btn btn-secondary ml-3 px-4">Back to List</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ForumApp/Views/Forums/Details.cshtml
@model ForumApp.Models.Forum

<!-- Include your custom CSS -->
<link rel="stylesheet" type="text/css" href="~/Content/Forum/ForumDetails.css" />
@Html.Partial("_Breadcrumb", ViewBag.Breadcrumbs as IEnumerable<ForumApp.Models.BreadcrumbItem>)


<div class="forum-details">
    <h2 class="forum-title">@Model.Title</h2>
    <p class="forum-description">@Model.Description</p>

    <h3 class="section-title">Posts</h3>

    @if (Model.Posts.Any(p => p.IsApproved))
    {
        <table id="postsTable" class="table table-striped table-hover table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayNameFor(m => m.Title)</th>
                    <th>Content</th>
                    <th>Date Created</th>
                    <th>Comments</th>
                    <th>User</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var post in Model.Posts.Where(p => p.IsApproved))
                {
                    <tr>
                        <td>@Html.ActionLink(post.Title, "Details", "Posts", new { id = post.PostId }, null)</td>
                        <td>@post.Content</td>
                        <td>@post.DateCreated.ToString("MMMM dd, yyyy")</td>
                        <td>
                            @post.Comments.Count
                        </td>
                        <td>
                            <div class="d-flex align-items-center">
                                @Html.ActionLink(post.User.UserName, "Index", "Profile", new { id = post.UserId }, new { @class = "username-link text-dark" })
                                <img src="@post.User.ProfilePictureUrl" alt="Profile Picture" class="profile-picture ml-2" style="width:40px; height:40px;" />
                            </div>
                        </td>
                        <td>
                            @if (User.IsInRole("Admin"))
                            {
                                <button data-post-id="@post.PostId" class="btn btn-sm btn-danger js-delete">
                                    <i class="fas fa-trash"></i> Delete
                                </button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="text-muted">No posts yet. Be the first to post!</p>
    }

    <div class="my-4">
        @if (User.Identity.IsAuthenticated)
        {
        @Html.ActionLink("Create New Post", "Create", "Posts", new { forumId = Model.ForumId }, new { @class = "btn btn-primary" })
        }
        @*@Html.ActionLink("Back to Forum List", "Index", null, new { @class = "btn btn-secondary ml-2" })*@
    </div>
</div>

@section Scripts {
    <script>

        var isAdmin = @Json.Encode(ViewBag.IsAdmin);
        var isMod = @Json.Encode(ViewBag.Mod);

$(document).ready(function () {
    var forumId = '@Model.ForumId';  // Get the forumId from the Razor model

    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('postSubmitted') === 'True') {
        bootbox.alert({
            title: "Post Submitted",
            message: "Your post has been successfully submitted!\nYou need to wait to get it approved by an admin!",
        });
    }

    var table = $('#postsTable').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "@Url.Action("GetPosts", "Forums")",  // Server-side action to load data
            "type": "POST",
            "data": function (d) {
                d.forumId = forumId;  // Pass forumId to the server
            }
        },
        "columns": [
            { "data": "Title", "render": function (data, type, row) {
                return `<a href='/Posts/Details/${row.PostId}'>${data}</a>`;
            }},
            { "data": "Content" },
            { "data": "DateCreated", "render": function (data, type, row) {
                return data;
            }},
            { "data": "CommentsCount" },
            { "data": "User", "render": function (data, type, row) {
                return `
                    <div class="d-flex align-items-center">
                        <a href='/Profile/Index/${data.UserId}' class='username-link text-dark'>${data.UserName}</a>
                        <img src='${data.ProfilePictureUrl}' alt='Profile Picture' class='profile-picture ml-2' style='width:40px; height:40px;' />
                    </div>`;
            }},
            {
                "data": "PostId", "render": function (data, type, row) {
                    if (isAdmin || isMod) {
                        return `<button data-post-id="${data}" class="btn btn-sm btn-danger js-delete">
                          Delete
                        </button>`;
                    } else {
                        return '';
                    }
            }}
        ]
    });

    // Delete post functionality
    $('#postsTable').on('click', '.js-delete', function () {
        var button = $(this);
        var postId = button.attr("data-post-id");

        console.log("Delete button clicked for post ID:", postId);
        bootbox.confirm("Are you sure you want to delete this post?", function (result) {
            if (result) {
                $.ajax({
                    url: "/Posts/DeletePost/" + postId,
                    method: "GET",
                    success: function () {
                        console.log("Post deleted successfully");
                        table.row(button.parents("tr")).remove().draw();
                    },
                    error: function (err) {
                        console.log(err);
                        bootbox.alert("An error occurred while deleting the post.");
                    }
                });
            }
        });
    });
});


    </script>
}

ForumApp/Views/Forums/Index.cshtml
@model IEnumerable<ForumApp.Models.Forum>

@{
    ViewBag.Title = "NikolaForums";
}


@Html.Partial("_Breadcrumb", ViewBag.Breadcrumbs as IEnumerable<ForumApp.Models.BreadcrumbItem>)

<link rel="stylesheet" type="text/css" href="~/Content/Forum/ForumDetails.css" />

<!-- Add Bootstrap classes for spacing and layout -->
<div class="container mt-5">
    <h2 class="text-center mb-4">@ViewBag.Title</h2>

    <!-- Card layout for forums -->
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Forums List</h4>
        </div>

        <div class="card-body">
            <!-- Add table responsive wrapper for better mobile support -->
            <div class="table-responsive">
                <table id="forumsTable" class="table table-striped table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.Title)</th>
                            <th>@Html.DisplayNameFor(m => m.Description)</th>
                            <th>Posts</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var forum in Model)
                        {
                            <tr>
                                <td>
                                    <h5>@Html.ActionLink(forum.Title, "Details", new { id = forum.ForumId }, new { @class = "text-decoration-none text-primary" })</h5>
                                </td>
                                <td>@Html.DisplayFor(m => forum.Description)</td>
                                <td><span class="badge badge-info text-dark">@forum.Posts.Where(p => p.IsApproved).Count()</span></td>
                                <td>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <button data-forum-id="@forum.ForumId" class="btn btn-danger btn-sm js-delete">
                                            <i class="fas fa-trash-alt"></i> Delete
                                        </button>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer text-right">
            @if (User.IsInRole("Admin"))
            {

                @Html.ActionLink("Create New Forum", "Create", new { }, new { @class = "btn btn-success" })
            }
        </div>
    </div>
</div>

<!-- Scripts section -->
@section Scripts {
    <script>

        var isAdmin = @Json.Encode(ViewBag.IsAdmin);
        $(document).ready(function () {
            // Initialize DataTables with server-side processing
            var table = $('#forumsTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "@Url.Action("GetForums", "Forums")",  // Server-side action to load data
                    "type": "POST"
                },
                "columns": [
                    { "data": "Title", "render": function (data, type, row) {
                        return `<h5><a href='/Forums/Details/${row.ForumId}' class='text-decoration-none text-primary'>${data}</a></h5>`;
                    }},
                    { "data": "Description" },
                    { "data": "PostsCount", "render": function (data, type, row) {
                        return `<span class="badge badge-info text-dark">${data}</span>`;
                    }},
                    {
                        "data": "ForumId", "render": function (data, type, row) {
                            if (isAdmin) {
                                return `<button data-forum-id="${data}" class="btn btn-danger btn-sm js-delete">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </button>`;
                            } else {
                                return ''
                            }
                    }}
                ]
            });

            // Use event delegation to handle the delete button dynamically
            $("#forumsTable").on("click", ".js-delete", function () {
                var button = $(this);
                var forumId = button.attr("data-forum-id");

                // Confirm deletion
                bootbox.confirm("Are you sure you want to delete this forum?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Forums/DeleteForum/" + forumId,
                            method: "GET",
                            success: function () {
                                // Remove the row from DataTables and redraw the table
                                table.row(button.parents("tr")).remove().draw();
                            },
                            error: function (err) {
                                console.log("Error deleting forum:", err);
                                bootbox.alert("An error occurred while deleting the forum.");
                            }
                        });
                    }
                });
            });
        });
    </script>
}

ForumApp/Views/Forums/_ForumListPartial.cshtml
@model IEnumerable<ForumApp.Models.Forum>

@foreach (var forum in Model)
{
    <div>
        <h3>@Html.ActionLink(forum.Title, "Details", new { id = forum.ForumId })</h3>
        <p>@forum.Description</p>
    </div>
}